version: '2'
services:
    yuri-app:
        image: yuri
        external_links:
            - yuri-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yuri?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    yuri-mysql:
        extends:
            file: mysql.yml
            service: yuri-mysql
